version : 0.2

env:
  variables:
    TEMPLATE_FILE: 'template.yaml'

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - pip install awscli==1.19.*
      - aws --version

  build:
    commands:
      - sam build
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file packaged-template.yaml
                    --image-repository $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/demo-app
                    
artifacts:
  type: zip
  files:
    - packaged-template.yaml


