version : 0.2

env:
  variables:
    TEMPLATE_FILE: 'template.yaml'

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - pip install awscli==1.19.*
      - aws --version

  build:
    commands:
      - sam build
      - sam package --template-file template.yaml --output-template-file packaged-template.yaml --s3-bucket my-test-app-phil-bucket
                    --image-repository 658251713809.dkr.ecr.eu-west-2.amazonaws.com/demo-app
      - cat packaged-template.yaml

artifacts:
  type: zip
  files:
    - packaged-template.yaml
